
DROP DATABASE IF EXISTS `OPTIONS`;
CREATE DATABASE `OPTIONS` /*!40100 COLLATE 'utf8_general_ci' */;
USE `OPTIONS`;
CREATE TABLE `SP500` (
	`YAHOO_CODE` VARCHAR(8) NULL,
	`NAME` VARCHAR(50) NULL,
	`SECTOR` VARCHAR(50) NULL
)
COMMENT='SP500 Index components'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
CREATE TABLE `OPTION_CHAINS` (
	`YAHOO_CODE` VARCHAR(8) NULL DEFAULT NULL,
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`STRIKE` DOUBLE NULL DEFAULT NULL,
	`EXPIRY` DATE NULL DEFAULT NULL,
	`CREATED` TIMESTAMP NULL DEFAULT NULL,
	INDEX `OPTION_CHAINS_INDEX_1` (`CONTRACT`)
)
COMMENT='Options Chains ISINs mapped to Yahoo Codes'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `OPTION_PRICES` (
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`UPDATED` DATETIME NULL DEFAULT NULL,
	`OPEN` DOUBLE NULL DEFAULT NULL,
	`BID` DOUBLE NULL DEFAULT NULL,
	`ASK` DOUBLE NULL DEFAULT NULL,
	INDEX `OPTION_PRICES_INDEX_1` (`CONTRACT`,`UPDATED`)
)
COMMENT='Option price data from Yahoo Finance'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `OPTION_OPEN_INTEREST` (
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`OPEN_INTEREST` INT(11) NULL DEFAULT NULL,
	INDEX `OPTION_OPEN_INTEREST_INDEX_1` (`CONTRACT`)
)
COMMENT='Open interest data from Yahoo Finance'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
CREATE TABLE `SP500_MEM` (
	`YAHOO_CODE` VARCHAR(8) NULL,
	`NAME` VARCHAR(50) NULL,
	`SECTOR` VARCHAR(50) NULL
)
COMMENT='SP500 Index components - memory table'
COLLATE='utf8_general_ci'
ENGINE=MEMORY;
CREATE TABLE `OPTION_CHAINS_MEM` (
	`YAHOO_CODE` VARCHAR(8) NULL DEFAULT NULL,
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`STRIKE` DOUBLE NULL DEFAULT NULL,
	`EXPIRY` DATE NULL DEFAULT NULL,
	`CREATED` TIMESTAMP NULL DEFAULT NULL,
	INDEX `OPTION_CHAINS_INDEX_1` (`CONTRACT`)
)
COMMENT='Options Chains ISINs mapped to Yahoo Codes - memory table'
COLLATE='utf8_general_ci'
ENGINE=MEMORY;
CREATE TABLE `OPTION_PRICES_MEM` (
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`UPDATED` DATETIME NULL DEFAULT NULL,
	`OPEN` DOUBLE NULL DEFAULT NULL,
	`BID` DOUBLE NULL DEFAULT NULL,
	`ASK` DOUBLE NULL DEFAULT NULL,
	INDEX `OPTION_PRICES_INDEX_1` (`CONTRACT`,`UPDATED`)
)
COMMENT='Option price data from Yahoo Finance - memory table'
COLLATE='utf8_general_ci'
ENGINE=MEMORY;
CREATE TABLE `OPTION_OPEN_INTEREST_MEM` (
	`CONTRACT` VARCHAR(50) NULL DEFAULT NULL,
	`OPEN_INTEREST` INT(11) NULL DEFAULT NULL,
	INDEX `OPTION_OPEN_INTEREST_INDEX_1` (`CONTRACT`)
)
COMMENT='Open interest data from Yahoo Finance - memory table'
COLLATE='utf8_general_ci'
ENGINE=MEMORY;
CREATE TABLE `STOCK_PRICES` (
	`YAHOO_CODE` VARCHAR(8) NULL DEFAULT NULL,
	`UPDATED` DATETIME NULL DEFAULT NULL,
	`OPEN` DOUBLE NULL DEFAULT NULL,
	`BID` DOUBLE NULL DEFAULT NULL,
	`ASK` DOUBLE NULL DEFAULT NULL,
	INDEX `STOCK_PRICES_INDEX_1` (`YAHOO_CODE`, `UPDATED`)
)
COMMENT='Stock prices for SP500 index components'
ENGINE=InnoDB;
CREATE TABLE `STOCK_PRICES_MEM` (
	`YAHOO_CODE` VARCHAR(8) NULL DEFAULT NULL,
	`UPDATED` DATETIME NULL DEFAULT NULL,
	`OPEN` DOUBLE NULL DEFAULT NULL,
	`BID` DOUBLE NULL DEFAULT NULL,
	`ASK` DOUBLE NULL DEFAULT NULL,
	INDEX `STOCK_PRICES_INDEX_1` (`YAHOO_CODE`, `UPDATED`)
)
COMMENT='Stock prices for SP500 index components - memory table'
ENGINE=MEMORY;
FLUSH PRIVILEGES;
CREATE USER 'OPTIONS_USER'@'localhost' IDENTIFIED BY 'OPTIONS_USER';
GRANT USAGE ON *.* TO 'OPTIONS_USER'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `OPTIONS`.* TO 'OPTIONS_USER'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'OPTIONS_USER'@'localhost';







